### ISSUE TITLE
Trong tuần qua chưa thấy nhóm cập nhật gì thêm

### ISSUE THREAD

**Issue by maytinhdibo** [ndtai772/MyBookList#9]

**Comment by taind772** [comment]
Bọn em cập nhật hơi muộn
trong tuần qua em có setup postgres db trên môi trường dev bằng docker và viết CRUD cơ bản trên các resources

Còn bạn @ducminh512 có bắt đầu viết phần frontend bằng ReactNative ở https://github.com/ducminh512/Frontend
em có hỏi thì bạn ấy bảo cần clean up rồi mới link vào repo này sau ạ
